name: CI on repository_dispatch

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print payload
        run: |
          echo "Received repository_dispatch event"
          echo "GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME"
          jq . < $GITHUB_EVENT_PATH || true

      # add your real build steps here, e.g. run tests / build / deploy
      - name: Example build step
        run: |
          echo "Run build..."